print("Camisa 10")
print("Turma do Pagode")

print("---------------------")

print("Se um dia eu disser que não te amo")
print("É que eu te amo ainda mais, pode acreditar")
print("Se um dia eu disser que não te quero")
print("É que eu te quero o dobro ou mais, tenta imaginar")
print("Não sei mentir, meus olhos dizem mais que minha boca")
print("Eu vejo que não tem saída, esse teu jeito meio louca")
print("Me faz feliz, amor que vai durar pra toda a vida")
print("Eu não me separo de você, mulher")
print("Nem se a Globeleza um dia me quiser")
print("Se na Mega-Sena eu vencer")
print("Fico com você, fico com você")
print("Se no Barcelona eu for camisa 10")
print("Me cobrir de ouro da cabeça aos pés")
print("Mesmo assim, se isso acontecer")
print("Fico com você, fico com você")
print("Eu não me separo de você, mulher")
print("Nem se a Globeleza um dia me quiser")
print("Se na Mega-Sena eu vencer")
print("Fico com você, fico com você")
print("Se no Barcelona eu for camisa 10")
print("Me cobrir de ouro da cabeça aos pés")