print("=== Exercício 20: Três Valores em Ordem Crescente ===")
a = int(input("Valor 1: "))
b = int(input("Valor 2: "))
c = int(input("Valor 3: "))
lista = sorted([a, b, c])
print("Ordem crescente:", lista)